const IMG_TREE = {
  abuse: {
    'mom.jpg': null,
    'cindy.jpg': null,
    'darren.jpg': null,
    'Drip.jpg': null,
    'ITURNED14INQUARANTINE.jpg': null,
    'MVP.jpg': null,
    'dog.jpg': null,
    'fullboardingpass.jpg': null,
    'grandma.jpg': null,
    'grandma_and_grandpa.jpg': null,
    'grandpa.png': null,
    'how_do_u_gain_20lb.jpg': null,
    'jakey_and_calamari.jpg': null,
    'jeter.png': null,
    'myjacobcurriethatiown.jpg': null,
    'patriot.jpg': null,
    'rip_gramps.jpg': null,
    'uncle.png': null,
    'matt.png': null,
    'ozzy.png': null,
    'penny.png': null,
    'jessica.png': null,
    'mom_breaches.txt': null,
  },
  profit: {
    'profitface.png': null,
  },
};
